[project]
name = "associate-data-scientist-in-python"
version = "0.1.0"
description = "This contains my learning notes, codes from datacamp course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
]
